import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Search } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
       
      
      <body className="min-h-full flex flex-col">

        <nav className="sticky top-0 h-16  w-full bg-purple-900 flex justify-between items-center">
        <div>
       <h1 className="text-3xl font-extrabold "> AudioPlayer</h1>

        </div>
       <div className="text-white flex items-center">
       <Search className="absolute ml-2"/>
        <input type="text" className="border rounded-xl hover:rounded-xxl h-8 w-80 bg-gray-200/30 pl-10  hover:w-120 transition-all duration-200 outline-none" />
       </div>
       <div>
        <input type="file" placeholder="insert audio"/>
       </div>
      </nav>

        {children}</body>
     
    </html>
  );
}
